import tkinter
from tkinter import *
from tkinter import ttk
from tkinter import messagebox
import pymysql
t=tkinter.Tk()
t.geometry('800x800')
def finddata():
    db=pymysql.connect(host='localhost',user='root',password='root',database='scm')
    cur=db.cursor()
    xa=int(e1.get())
    sql="select custid,productid,serviceid,engid,dateofcall,dateofsolve,estbill from callregisters where callid=%d"%(xa)
    cur.execute(sql)
    data=cur.fetchone()
    e2.delete(0,END)
    e2.insert(0,data[0])
    e3.delete(0,END)
    e3.insert(0,str(data[1]))
    e4.delete(0,END)
    e4.insert(0,str(data[2]))
    e5.delete(0,END)
    e5.insert(0,str(data[3]))
    e6.delete(0,END)
    e6.insert(0,str(data[4]))
    e7.delete(0,END)
    e7.insert(0,str(data[5]))
    e8.delete(0,END)
    e8.insert(0,str(data[6]))
def updatedata():
    db=pymysql.connect(host='localhost',user='root',password='root',database='scm')
    cur=db.cursor()
    xa=int(e1.get())
    xb=int(e2.get())
    xc=int(e3.get())
    xd=int(e4.get())
    xe=int(e5.get())
    xf=e6.get()
    xg=e7.get()
    xh=int(e8.get())
    sql="update callregisters set custid='%d',productid='%d', serviceid='%d',engid=%d,dateofcall='%s',dateofsolve='%s',estbill=%d where callid=%d"%(xb,xc,xd,xe,xf,xg,xh,xa)
    cur.execute(sql)
    db.commit()
    db.close()
    messagebox.showinfo('hi','data updated')
    e1.delete(0,END)
    e2.delete(0,END)
    e3.delete(0,END)
    e4.delete(0,END)
    e5.delete(0,END)
    e6.delete(0,END)
    e7.delete(0,END)
    e8.delete(0,END)
   
def fillid():
    db=pymysql.connect(host='localhost',user='root',password='root',database='scm')
    cur=db.cursor()
    xb=[]
    sql="select callid from callregisters"
    cur.execute(sql)
    data=cur.fetchall()
    for res in data:
        xb.append(res[0])
    e1['values']=xb
    db.close()
a=Label(t,text='callid')
a.place(x=50,y=60)
e1=ttk.Combobox(t)
fillid()
e1.place(x=450,y=60)

bt=Button(t,text='find',command=finddata)
bt.place(x=50,y=100)

b=Label(t,text='custid')
b.place(x=50,y=140)
e2=Entry(t,width=30)
e2.place(x=450,y=140)
g=Label(t,text='productid')
g.place(x=50,y=180)
e3=Entry(t,width=30)
e3.place(x=450,y=180)

h=Label(t,text='serviceid')
h.place(x=50,y=220)
e4=Entry(t,width=30)
e4.place(x=450,y=220)

g=Label(t,text='engid')
g.place(x=50,y=260)
e5=Entry(t,width=30)
e5.place(x=450,y=260)
h=Label(t,text='dateofcall')
h.place(x=50,y=300)
e6=Entry(t,width=30)
e6.place(x=450,y=300)
i=Label(t,text='dateofsolve')
i.place(x=50,y=340)
e7=Entry(t,width=30)
e7.place(x=450,y=340)
k=Label(t,text='estbill')
k.place(x=50,y=400)
e8=Entry(t,width=30)
e8.place(x=450,y=400)
bt=Button(t,text='update',command=updatedata)
bt.place(x=50,y=450)


t.mainloop()